Add RawAudio class and 'save to wav'
huggingface/transformers.js pull request #682
Opened 2024-04-05 09:18 UTC by Th3G33k

Following messages from #680 

The 'save to wav' is my own simple implementation, using [file specs](https://fr.wikipedia.org/wiki/Waveform_Audio_File_Format), and hex viewer of a generated wav file.

Below the changes :
- added `RawAudio` class, with `.save(path)` (support browser, webworker and nodejs)
- modified some audio pipeline, to return `RawAudio` object
- added properties `isBrowserEnv` and `isWebworkerEnv` to env

Example use :
```js
const synthesizer = await pipeline('text-to-speech', 'Xenova/mms-tts-eng');
const output = await synthesizer('Hello, my dog is cute');
output.save("audio.wav");
```

2024-04-10 15:14 UTC, xenova requested changes
Thanks for this! Just some questions/suggestions:

2024-04-10 15:14 UTC, xenova commented on src/pipelines.js
> +        return new RawAudio (
```suggestion
        return new RawAudio(
```

2024-04-10 15:14 UTC, xenova commented on src/pipelines.js
> +        return new RawAudio (
```suggestion
        return new RawAudio(
```

2024-04-10 15:14 UTC, xenova commented on src/utils/audio.js
> +     * Wav file specs : https://fr.wikipedia.org/wiki/Waveform_Audio_File_Format
```suggestion
     * WAV file specs : https://en.wikipedia.org/wiki/Waveform_Audio_File_Format
```

2024-04-10 15:14 UTC, xenova commented on src/utils/audio.js
> +            }
Throwing an error earlier would be preferable.

2024-04-10 15:14 UTC, xenova commented on src/utils/audio.js
> +            throw new Error('Unable to save because filesystem is disabled in this environment.')
Same as before - better to throw the error before writing the buffer.

2024-04-10 15:14 UTC, xenova commented on src/utils/audio.js
> +            downloadLink.remove();
Similar code to `RawImage.save`, so we can abstract this a little bit.

2024-04-10 15:14 UTC, xenova commented on src/utils/audio.js
> +        buf_size = audio.buffer.byteLength
This suggests a maximum buffer size? Could we throw an error if this is larger than allowed?

2024-04-11 09:41 UTC, Th3G33k commented
Thank you @xenova for the review.

Here's the changes I have made :
- split into two functions : `toBlob()` and `save(path)`
- check type in `constructor()`
- in `save()`, check running environment first before proceeding
- reduce memory footprint, by using `new Blob([wav_header, audio])` instead of allocating additional TypedArray `new Uint8Array(buf_size + wav_header.length)`

2024-04-12 00:39 UTC, xenova commented
Thanks! 🤗 Would you mind benchmarking your code against https://www.npmjs.com/package/audiobuffer-to-wav, which I used in a [demo](https://github.com/xenova/transformers.js/blob/8804c36591d11d8456788d1bb4b16489121b3be2/examples/text-to-speech-client/src/utils.js) a few months ago.

Other than that, I like the abstractions you introduced for the `RawImage` and `RawAudio` classes, and this will be perfect to merge into the v3 branch for my musicgen demo I'm working on 🔥

2024-04-12 10:46 UTC, Th3G33k commented
I have added support for 2 channels audio + interleave.

`interleave(keepOriginalValues)` will use a new buffer of length * 2 (keeping original), or a new buffer of length * 1 (overwriting original audio data)

Below a quick benchmark, comparing with `encodeWAV(samples)` used in the demo.

```js
function benchmark(){
    let i, input, output

    console.time('encodeWAV')
    for(i=0; i<20000; i++){
        input = new Float32Array(i).fill(i)
        output = encodeWAV(input)
        output = new Blob([output])
    }
    console.timeEnd('encodeWAV')

    console.time('RawAudio')
    for(i=0; i<20000; i++){
        input = new Float32Array(i).fill(i)
        output = new RawAudio(input, 16000)
        output = output.toBlob()
    }
    console.timeEnd('RawAudio')
}

/*
encodeWAV: 3216.6669921875 ms
RawAudio: 2702.23291015625 ms
---
encodeWAV: 3296.2138671875 ms
RawAudio: 2768.235107421875 ms
*/
```

`encodeWAV` is slower, since it's hard copy all audio values, into a new Buffer.

```js
    for (let i = 0; i < samples.length; ++i, offset += 4) {
        view.setFloat32(offset, samples[i], true)
    }
```

2024-04-22 10:19 UTC, xenova commented
Thanks again! Just letting you know this PR is marked for the next release :)

2024-05-08 08:52 UTC, Th3G33k commented
I have merged branch v3 #545 into this PR

2025-01-15 11:26 UTC, xenova commented
Hey! 👋 This was merged in https://github.com/huggingface/transformers.js/commit/eb838195406dbf2cee955e75e627685700fd6b34! For now, we'll only support 1-channel (non-interleaved) wav files for simplicity.

![image](https://github.com/user-attachments/assets/8e02e20d-3fff-48e1-a807-ca223f80d53e)

2025-01-15 11:26 UTC, closed without merging